#!/usr/bin/env python3
"""
Validate Rust CLI output against Python reference.

This script compares fonts generated by the Rust CLI with those generated
by Python's fontTools to ensure identical output.

Usage:
    uv run python tests/validate_rust_output.py

Expected to FAIL until font-instancer implements:
    - MVAR interpolation
    - Bounding box recalculation
"""

import subprocess
import sys
import tempfile
from pathlib import Path

from fontTools.ttLib import TTFont

PROJECT_ROOT = Path(__file__).parent.parent
RUST_CLI = PROJECT_ROOT / "rust/warpnine-fonts/target/release/warpnine-fonts"
BUILD_DIR = PROJECT_ROOT / "build"
DIST_DIR = PROJECT_ROOT / "dist"


def run_rust_create_sans(output_dir: Path) -> bool:
    """Generate WarpnineSans fonts with Rust CLI."""
    result = subprocess.run(
        [
            str(RUST_CLI),
            "create-sans",
            "--input",
            str(BUILD_DIR / "Recursive_VF_1.085.ttf"),
            "--output-dir",
            str(output_dir),
        ],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def validate_mvar_metrics(rust_font: TTFont, python_font: TTFont) -> dict:
    """Validate MVAR-interpolated metrics."""
    results = {"pass": [], "fail": []}

    checks = [
        ("OS/2.sxHeight", rust_font["OS/2"].sxHeight, python_font["OS/2"].sxHeight),
        (
            "OS/2.yStrikeoutPosition",
            rust_font["OS/2"].yStrikeoutPosition,
            python_font["OS/2"].yStrikeoutPosition,
        ),
        (
            "OS/2.yStrikeoutSize",
            rust_font["OS/2"].yStrikeoutSize,
            python_font["OS/2"].yStrikeoutSize,
        ),
        (
            "post.underlinePosition",
            rust_font["post"].underlinePosition,
            python_font["post"].underlinePosition,
        ),
        (
            "post.underlineThickness",
            rust_font["post"].underlineThickness,
            python_font["post"].underlineThickness,
        ),
    ]

    for name, rs_val, py_val in checks:
        if rs_val == py_val:
            results["pass"].append(name)
        else:
            results["fail"].append(f"{name}: Rust={rs_val} Python={py_val}")

    return results


def validate_bounding_box(
    rust_font: TTFont, python_font: TTFont, tolerance: int = 2
) -> dict:
    """Validate bounding box values."""
    results = {"pass": [], "fail": []}

    checks = [
        ("head.xMin", rust_font["head"].xMin, python_font["head"].xMin),
        ("head.xMax", rust_font["head"].xMax, python_font["head"].xMax),
        ("head.yMin", rust_font["head"].yMin, python_font["head"].yMin),
        ("head.yMax", rust_font["head"].yMax, python_font["head"].yMax),
        (
            "hhea.minLeftSideBearing",
            rust_font["hhea"].minLeftSideBearing,
            python_font["hhea"].minLeftSideBearing,
        ),
        (
            "hhea.minRightSideBearing",
            rust_font["hhea"].minRightSideBearing,
            python_font["hhea"].minRightSideBearing,
        ),
        (
            "hhea.xMaxExtent",
            rust_font["hhea"].xMaxExtent,
            python_font["hhea"].xMaxExtent,
        ),
    ]

    for name, rs_val, py_val in checks:
        diff = abs(rs_val - py_val)
        if diff <= tolerance:
            results["pass"].append(name)
        else:
            results["fail"].append(
                f"{name}: Rust={rs_val} Python={py_val} (diff={diff})"
            )

    return results


def validate_table_tags(rust_font: TTFont, python_font: TTFont) -> dict:
    """Validate that both fonts have the same set of table tags."""
    results = {"pass": [], "fail": []}

    rs_tables = set(rust_font.keys())
    py_tables = set(python_font.keys())

    if rs_tables == py_tables:
        results["pass"].append(f"Table tags match ({len(rs_tables)} tables)")
    else:
        only_rust = rs_tables - py_tables
        only_python = py_tables - rs_tables
        if only_rust:
            results["fail"].append(f"Tables only in Rust: {sorted(only_rust)}")
        if only_python:
            results["fail"].append(f"Tables only in Python: {sorted(only_python)}")

    return results


def validate_features(rust_font: TTFont, python_font: TTFont) -> dict:
    """Validate GSUB/GPOS features."""
    results = {"pass": [], "fail": []}

    # GSUB
    rs_gsub = {r.FeatureTag for r in rust_font["GSUB"].table.FeatureList.FeatureRecord}
    py_gsub = {
        r.FeatureTag for r in python_font["GSUB"].table.FeatureList.FeatureRecord
    }

    if rs_gsub == py_gsub:
        results["pass"].append(f"GSUB features ({len(rs_gsub)})")
    else:
        only_rust = rs_gsub - py_gsub
        only_python = py_gsub - rs_gsub
        results["fail"].append(
            f"GSUB features differ: only_rust={only_rust}, only_python={only_python}"
        )

    # GPOS
    rs_gpos = {r.FeatureTag for r in rust_font["GPOS"].table.FeatureList.FeatureRecord}
    py_gpos = {
        r.FeatureTag for r in python_font["GPOS"].table.FeatureList.FeatureRecord
    }

    if rs_gpos == py_gpos:
        results["pass"].append(f"GPOS features ({len(rs_gpos)})")
    else:
        results["fail"].append("GPOS features differ")

    return results


def validate_core_metrics(rust_font: TTFont, python_font: TTFont) -> dict:
    """Validate core metrics that should always match."""
    results = {"pass": [], "fail": []}

    checks = [
        (
            "maxp.numGlyphs",
            rust_font["maxp"].numGlyphs,
            python_font["maxp"].numGlyphs,
        ),
        (
            "OS/2.usWeightClass",
            rust_font["OS/2"].usWeightClass,
            python_font["OS/2"].usWeightClass,
        ),
        (
            "OS/2.usWidthClass",
            rust_font["OS/2"].usWidthClass,
            python_font["OS/2"].usWidthClass,
        ),
        (
            "head.unitsPerEm",
            rust_font["head"].unitsPerEm,
            python_font["head"].unitsPerEm,
        ),
    ]

    for name, rs_val, py_val in checks:
        if rs_val == py_val:
            results["pass"].append(name)
        else:
            results["fail"].append(f"{name}: Rust={rs_val} Python={py_val}")

    return results


def validate_font_pair(rust_path: Path, python_path: Path) -> tuple[int, int, list]:
    """Validate a single font pair. Returns (pass_count, fail_count, failures)."""
    rust_font = TTFont(rust_path)
    python_font = TTFont(python_path)

    all_pass = []
    all_fail = []

    # Table tags (should always pass)
    tables = validate_table_tags(rust_font, python_font)
    all_pass.extend(tables["pass"])
    all_fail.extend(tables["fail"])

    # Core metrics (should always pass)
    core = validate_core_metrics(rust_font, python_font)
    all_pass.extend(core["pass"])
    all_fail.extend(core["fail"])

    # Features (should always pass)
    features = validate_features(rust_font, python_font)
    all_pass.extend(features["pass"])
    all_fail.extend(features["fail"])

    # MVAR metrics (may fail until font-instancer is fixed)
    mvar = validate_mvar_metrics(rust_font, python_font)
    all_pass.extend(mvar["pass"])
    all_fail.extend(mvar["fail"])

    # Bounding box (may fail until font-instancer is fixed)
    bbox = validate_bounding_box(rust_font, python_font)
    all_pass.extend(bbox["pass"])
    all_fail.extend(bbox["fail"])

    rust_font.close()
    python_font.close()

    return len(all_pass), len(all_fail), all_fail


def main():
    print("=" * 70)
    print("Rust CLI Output Validation")
    print("=" * 70)

    # Check prerequisites
    if not RUST_CLI.exists():
        print(f"\nERROR: Rust CLI not found at {RUST_CLI}")
        print("Run: cargo build --release")
        sys.exit(1)

    recursive_vf = BUILD_DIR / "Recursive_VF_1.085.ttf"
    if not recursive_vf.exists():
        print(f"\nERROR: Source VF not found at {recursive_vf}")
        print("Run: warpnine-fonts download")
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        rust_out = tmp_dir / "rust"
        rust_out.mkdir()

        print("\nGenerating Rust fonts...")
        if not run_rust_create_sans(rust_out):
            print("ERROR: Rust CLI failed")
            sys.exit(1)

        print("Comparing with Python reference...\n")

        styles = [
            "Light",
            "Regular",
            "Medium",
            "Bold",
            "Black",
            "Italic",
            "LightItalic",
            "BoldItalic",
        ]

        total_pass = 0
        total_fail = 0
        all_failures = []

        for style in styles:
            rust_font = rust_out / f"WarpnineSans-{style}.ttf"
            python_font = DIST_DIR / f"WarpnineSans-{style}.ttf"

            if not rust_font.exists():
                print(f"{style}: SKIPPED (Rust font not found)")
                continue
            if not python_font.exists():
                print(f"{style}: SKIPPED (Python reference not found)")
                continue

            pass_count, fail_count, failures = validate_font_pair(
                rust_font, python_font
            )
            total_pass += pass_count
            total_fail += fail_count

            if fail_count == 0:
                print(f"{style}: ✓ PASS ({pass_count} checks)")
            else:
                print(f"{style}: ✗ FAIL ({pass_count} pass, {fail_count} fail)")
                for f in failures:
                    print(f"    - {f}")
                    all_failures.append(f"{style}: {f}")

        print("\n" + "=" * 70)
        print(f"Total: {total_pass} passed, {total_fail} failed")
        print("=" * 70)

        if total_fail == 0:
            print("\nRESULT: ALL VALIDATIONS PASSED ✓")
            print("\nThe Rust CLI produces identical output to Python!")
            sys.exit(0)
        else:
            print("\nRESULT: SOME VALIDATIONS FAILED ✗")
            print("\nExpected failures until font-instancer fixes:")
            print("  - MVAR interpolation (sxHeight, strikeout, underline)")
            print("  - Bounding box recalculation (head.xMin/xMax/yMin/yMax)")
            print(
                "  - hhea extents (minLeftSideBearing, minRightSideBearing, xMaxExtent)"
            )
            print("\nSee: rust/warpnine-fonts/VALIDATION.md for details")
            sys.exit(1)


if __name__ == "__main__":
    main()
